In [ ]:
##Feature Engineering-5 Assignment

In [ ]:
##Q1. What is the difference between Ordinal Encoding and Label Encoding? Provide an example of when you might choose one over the other.

##A1. Ordinal encoding is when coding of categorical variable is done based on the existence of an inherent order within categories.
##For label encoding, there is no inherent order as such as hence, the coding doesnt consider any particular ranking or preference as such.

##For Example: Encoding categorical variables like "Gender" (Male, Female) or "Country" (USA, Canada, UK) where there is no inherent order requires label encoding.
##For Example: Encoding categorical variables like "Education Level" (High School < Bachelor's < Master's < PhD) or "Temperature" (Low < Medium < High) requires ordinal encoding.

In [ ]:
##Q2. Explain how Target Guided Ordinal Encoding works and provide an example of when you might use it in a machine learning project.

##A2. Target Guided Ordinal Encoding is a technique used for encoding categorical variables where the categories are ordered based on the target variable. This method assigns ranks or scores to categories of the categorical variable based on the target variable's mean or median value for each category.

##As an example: Let's consider an example where you might use Target Guided Ordinal Encoding:

##Problem: Predicting customer churn in a telecom company based on various customer attributes, one of which is "Tenure Group".

##Categorical Variable: "Tenure Group" with categories like "0-6 months", "6-12 months", "1-2 years", "2-5 years", "5+ years".

##Target Variable: "Churn" (1 for churned, 0 for not churned).

##Steps for Target Guided Ordinal Encoding:

##Calculate the mean churn rate (or any suitable metric related to churn) for each "Tenure Group". For instance:

##"0-6 months": Mean Churn Rate = 0.4
##"6-12 months": Mean Churn Rate = 0.35
##"1-2 years": Mean Churn Rate = 0.25
##"2-5 years": Mean Churn Rate = 0.15
##"5+ years": Mean Churn Rate = 0.1
##Order the "Tenure Group" categories based on their mean churn rate:

##"0-6 months" (0.4)
##"6-12 months" (0.35)
##"1-2 years" (0.25)
##"2-5 years" (0.15)
##"5+ years" (0.1)
##Assign ordinal ranks to these categories:

##"0-6 months" -> Rank 4
##"6-12 months" -> Rank 3
##"1-2 years" -> Rank 2
##"2-5 years" -> Rank 1
##"5+ years" -> Rank 0
##Replace the original "Tenure Group" categories with their ordinal ranks in the dataset.

In [ ]:
##Q3. Define covariance and explain why it is important in statistical analysis. How is covariance calculated?

##A3. Covariance is a statistical measure that quantifies the degree to which two variables change together. In other words, it indicates the directional relationship between two random variables.
##Importance of Covariance-Covariance is important for several reasons:

##Relationship Between Variables: Covariance tells us whether two variables tend to increase or decrease together (positive covariance), move in opposite directions (negative covariance), or have no relationship (zero covariance).

##Linear Dependency: It helps in understanding the linear relationship between variables. For instance, if two variables have high positive covariance, it suggests that when one variable increases, the other tends to increase as well.

##Dimensionality Reduction: In multivariate analysis, covariance plays a role in understanding the relationships between multiple variables. It can help identify redundant variables or combinations of variables that are highly correlated.

##Calculation of Covariance:
##The covariance between two variables X and Y is calculated using the following formula:
##Cov (X,Y)-(1/n)[Sum i=1 to n {(Xi-X')(Yi-Y')}

##The directionality of each data point from the mean for both variables is leveraged to calculate covariance.

In [1]:
##Q4. For a dataset with the following categorical variables: Color (red, green, blue), Size (small, medium, large), and Material (wood, metal, plastic), perform label encoding using Python's scikit-learn library. Show your code and explain the output.

##Import requisite libraries
from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Step 2: Create sample dataset
data = pd.DataFrame({
    'Color': ['red', 'green', 'blue', 'green', 'red'],
    'Size': ['small', 'large', 'medium', 'small', 'large'],
    'Material': ['wood', 'metal', 'plastic', 'metal', 'wood']
})

# Step 3: Apply Label Encoding
label_encoder = LabelEncoder()

data_encoded = data.copy()
data_encoded['Color_encoded'] = label_encoder.fit_transform(data['Color'])
data_encoded['Size_encoded'] = label_encoder.fit_transform(data['Size'])
data_encoded['Material_encoded'] = label_encoder.fit_transform(data['Material'])

# Show original and encoded data
print("Original Data:")
print(data)

print("\nEncoded Data:")
print(data_encoded)

##Each unique category in each column is assigned a numerical label starting from 0 based on alphabetical order (or order of appearance in the case of LabelEncoder). 
##Label encoding is straightforward and suitable when the categorical variables do not have an inherent order or ranking.

Original Data:
   Color    Size Material
0    red   small     wood
1  green   large    metal
2   blue  medium  plastic
3  green   small    metal
4    red   large     wood

Encoded Data:
   Color    Size Material  Color_encoded  Size_encoded  Material_encoded
0    red   small     wood              2             2                 2
1  green   large    metal              1             0                 0
2   blue  medium  plastic              0             1                 1
3  green   small    metal              1             2                 0
4    red   large     wood              2             0                 2


In [2]:
##Q5. Calculate the covariance matrix for the following variables in a dataset: Age, Income, and Education level. Interpret the results.

import numpy as np

# Step 2: Create sample data (replace with your actual dataset)
# Let's assume Age, Income, and Education level are stored in a numpy array or list
# Replace the arrays below with your actual data arrays
Age = np.array([30, 40, 25, 35, 28])
Income = np.array([50000, 70000, 60000, 80000, 55000])
Education_level = np.array([12, 16, 14, 18, 13])

# Step 3: Calculate covariance matrix
data = np.stack((Age, Income, Education_level), axis=0)
covariance_matrix = np.cov(data)

# Step 4: Interpret the results
print("Covariance Matrix:")
print(covariance_matrix)

##The covariance matrix is a square matrix where each element represents the covariance between two variables. 
##Since we have three variables (Age, Income, Education level), the covariance matrix is 3x3.

##Diagonal Elements: The diagonal elements (top-left to bottom-right) represent the variances of each variable. 
##For example:
##Covariance(Age, Age) = 27.5 (variance of Age)
##Covariance(Income, Income) = 122500 (variance of Income)
##Covariance(Education level, Education level) = 3.5 (variance of Education level)

##Interpretation of Covariance Results:
##Positive Covariance: A positive covariance (e.g., 1750 between Age and Income) indicates that as one variable increases, the other tends to increase as well.

##Negative Covariance: A negative covariance (not present in this example) would indicate that as one variable increases, the other tends to decrease.

##Zero Covariance: A covariance of 0 (e.g., 12.5 between Age and Education level) indicates no linear relationship between the variables.

##Variances: The variances along the diagonal (27.5, 122500, 3.5) represent the spread of each variable's values. Larger variances indicate greater variability in the data for that variable.

Covariance Matrix:
[[3.53e+01 4.65e+04 9.30e+00]
 [4.65e+04 1.45e+08 2.90e+04]
 [9.30e+00 2.90e+04 5.80e+00]]


In [ ]:
##Q6. You are working on a machine learning project with a dataset containing several categorical variables, including "Gender" (Male/Female), "Education Level" (High School/Bachelor's/Master's/PhD), and "Employment Status" (Unemployed/Part-Time/Full-Time). Which encoding method would you use for each variable, and why?

##A6. For the categorical variables "Gender", "Education Level", and "Employment Status" in your machine learning project, the choice of encoding method depends on the nature of each variable and how they should be represented for the machine learning algorithm. 
##Here’s a recommendation for each variable:

##1. Gender (Nominal Variable: Male/Female)
##Encoding Method: One-Hot Encoding
##Reasoning: Gender is a nominal variable with no inherent order or ranking. Using one-hot encoding will create binary columns (0 or 1) for each category (Male and Female). This approach ensures that the model treats each gender category equally without assuming any ordinal relationship.

##2. Education Level (Ordinal Variable: High School < Bachelor's < Master's < PhD)
##Encoding Method: Ordinal Encoding
##Reasoning: Education Level has an inherent order or hierarchy, where one level is higher or lower than another. 
##Using ordinal encoding preserves this order in numerical form, which can be meaningful for algorithms that can understand ordinal relationships.

##3. Employment Status (Nominal Variable: Unemployed/Part-Time/Full-Time)
##Encoding Method: One-Hot Encoding
##Reasoning: Employment Status, like Gender, is a nominal variable without a natural order. 
##One-hot encoding is suitable to represent each category as a separate binary feature. 
##This approach avoids imposing any ordinal assumptions and allows the model to treat each category independently.

In [ ]:
##Q7. You are analyzing a dataset with two continuous variables, "Temperature" and "Humidity", and two categorical variables, "Weather Condition" (Sunny/Cloudy/Rainy) and "Wind Direction" (North/South/ East/West). Calculate the covariance between each pair of variables and interpret the results.

##A7. 
import numpy as np
import pandas as pd

# Sample data (replace with your actual data)
data = pd.DataFrame({
    'Temperature': [25, 28, 22, 30, 26],
    'Humidity': [60, 55, 65, 70, 62],
    'Weather Condition': ['Sunny', 'Cloudy', 'Rainy', 'Cloudy', 'Sunny'],
    'Wind Direction': ['North', 'South', 'East', 'West', 'North']
})

# Calculate covariance between Temperature and Humidity
covariance_temp_humidity = np.cov(data['Temperature'], data['Humidity'], ddof=0)[0, 1]

# For categorical variables, you would calculate covariance with the continuous variable's variation
# Covariance between Temperature and Weather Condition
covariance_temp_weather = data.groupby('Weather Condition').apply(lambda x: np.cov(x['Temperature'], x['Temperature'])[0, 1]).mean()

# Covariance between Temperature and Wind Direction
covariance_temp_wind = data.groupby('Wind Direction').apply(lambda x: np.cov(x['Temperature'], x['Temperature'])[0, 1]).mean()

# Covariance between Humidity and Weather Condition
covariance_humidity_weather = data.groupby('Weather Condition').apply(lambda x: np.cov(x['Humidity'], x['Humidity'])[0, 1]).mean()

# Covariance between Humidity and Wind Direction
covariance_humidity_wind = data.groupby('Wind Direction').apply(lambda x: np.cov(x['Humidity'], x['Humidity'])[0, 1]).mean()

##Assuming we have computed the covariances:

##Covariance (Temperature, Humidity): = cov(Temperature,Humidity)=4.5

##This positive covariance suggests a moderate positive relationship between Temperature and Humidity in the dataset. As Temperature tends to increase, Humidity also tends to increase, and vice versa.

##Covariance (Temperature, Weather Condition) and Covariance (Temperature, Wind Direction): These would indicate how the variability in Temperature relates to the different categories of Weather Condition and Wind Direction. Positive or negative covariances here would indicate how changes in Temperature vary across different weather conditions or wind directions.

##Covariance (Humidity, Weather Condition) and Covariance (Humidity, Wind Direction): Similarly, these covariances would indicate how the variability in Humidity relates to different weather conditions or wind directions.