In [1]:
##Numpy Basics Assignment

In [10]:
##Question 1:

import numpy as np

list_ = ['1' , '2' , '3' , '4' , '5']

array_list = np.array(object = list_)

In [11]:
type(list_)

list

In [12]:
type(array_list)

numpy.ndarray

In [ ]:
## There is difference in data types.

In [29]:
##Question 2
#Getting the data type of every element in the list
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [31]:
#Getting the data type of every element in the array
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [33]:
##Question 3:

array_list = np.array(object = list_, dtype = int)

In [34]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [35]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
## For question 3, the data type changed from str to int after making the change in the array_list variable.

In [32]:
##Question 4:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [22]:
np.shape(num_array)

(2, 3)

In [23]:
np.size(num_array)

6

In [24]:
##Question 5

arr1=np.zeros((3,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [26]:
##Question 6

arr_i=np.identity(5)
print(arr_i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
