In [1]:
##Statistics Advance-5 Assignment

In [2]:
##Q1. Calculate the 95% confidence interval for a sample of data with a mean of 50 and a standard deviation of 5 using Python. Interpret the results.

##A1. Below is the code:

import scipy.stats as stats

mean = 50
std_dev = 5
sample_size = 100  # Change this to your actual sample size

# Calculate standard error
std_error = std_dev / (sample_size ** 0.5)

# Calculate margin of error
margin_of_error = stats.norm.ppf(0.975) * std_error

# Calculate confidence interval
confidence_interval = (mean - margin_of_error, mean + margin_of_error)

print("95% Confidence Interval:", confidence_interval)


95% Confidence Interval: (49.02001800772997, 50.97998199227003)


In [8]:
##Q2. Conduct a chi-square goodness of fit test to determine if the distribution of colors of M&Ms in a bag matches the expected distribution of 20% blue, 20% orange, 20% green, 10% yellow, 10% red, and 20% brown. Use Python to perform the test with a significance level of 0.05.

##A2. Below is the code:

from scipy.stats import chisquare

# Observed frequencies of each color
observed = [20, 20, 20, 20, 10, 10]  # Example values, replace with actual counts

# Expected frequencies based on the expected distribution
expected = [0.2 * sum(observed)] * 4 + [0.1 * sum(observed)]*2

# Perform the chi-square test
chi2_stat, p_val = chisquare(observed, f_exp=expected)

# Print the results
print("Chi-square Statistic:", chi2_stat)
print("p-value:", p_val)

# Check significance level
alpha = 0.05
if p_val < alpha:
    print("Reject the null hypothesis. The distribution of M&M colors is significantly different from the expected distribution.")
else:
    print("Fail to reject the null hypothesis. The distribution of M&M colors matches the expected distribution.")


Chi-square Statistic: 0.0
p-value: 1.0
Fail to reject the null hypothesis. The distribution of M&M colors matches the expected distribution.


In [10]:
##Q3. Use Python to calculate the chi-square statistic and p-value for a contingency table with the following data:

##    Group A Group B

## Outcome1 20 15
## Outcome2 10 25
## Outcome3 15 20

##A3. 

from scipy.stats import chi2_contingency

# Create a contingency table (2x3)
observed = [
    [20, 10, 15],  # Factor 1 Level 1
    [15, 25, 20],  # Factor 1 Level 2
]

# Perform the chi-square test
chi2_stat, p_val, dof, expected = chi2_contingency(observed)

# Print the results
print("Chi-square Statistic:", chi2_stat)
print("p-value:", p_val)
print("Degrees of Freedom:", dof)
print("Expected Frequencies:")
print(expected)

# Check significance level
alpha = 0.05
if p_val < alpha:
    print("Reject the null hypothesis. There is a significant association between the two factors.")
else:
    print("Fail to reject the null hypothesis. There is no significant association between the two factors.")

Chi-square Statistic: 5.833333333333334
p-value: 0.05411376622282158
Degrees of Freedom: 2
Expected Frequencies:
[[15. 15. 15.]
 [20. 20. 20.]]
Fail to reject the null hypothesis. There is no significant association between the two factors.


In [1]:
##Q4. A study of the prevalence of smoking in a population of 500 individuals found that 60 individuals smoked. Use Python to calculate the 95% confidence interval for the true proportion of individuals in the population who smoke.

##A4. 

import statsmodels.stats.proportion as prop

# Sample size
n = 500

# Number of individuals who smoke
x = 60

# Calculate the proportion
p_hat = x / n

# Calculate the confidence interval
conf_interval = prop.proportion_confint(x, n, alpha=0.05, method='normal')

print("95% Confidence Interval for the proportion of smokers:", conf_interval)


95% Confidence Interval for the proportion of smokers: (0.09151638887130706, 0.14848361112869293)


In [2]:
##Q5. Calculate the 90% confidence interval for a sample of data with a mean of 75 and a standard deviation of 12 using Python. Interpret the results.

##A5. 
import scipy.stats as stats

# Sample mean
mean = 75

# Standard deviation
std_dev = 12

# Sample size (assuming it's large enough for the normal distribution approximation)
sample_size = 100

# Confidence level
confidence_level = 0.90

# Calculate the standard error
std_error = std_dev / (sample_size ** 0.5)

# Calculate the margin of error
margin_of_error = stats.norm.ppf((1 + confidence_level) / 2) * std_error

# Calculate the confidence interval
lower_bound = mean - margin_of_error
upper_bound = mean + margin_of_error

print("90% Confidence Interval:", (lower_bound, upper_bound))

90% Confidence Interval: (73.02617564765823, 76.97382435234177)


In [3]:
##Q6. Use Python to plot the chi-square distribution with 10 degrees of freedom. Label the axes and shade the area corresponding to a chi-square statistic of 15.

##A6. 
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

# Define the degrees of freedom
df = 10

# Generate x values for the plot
x = np.linspace(0, 30, 1000)

# Calculate the chi-square probability density function (PDF) for the given degrees of freedom
pdf = stats.chi2.pdf(x, df)

# Plot the chi-square distribution
plt.plot(x, pdf, label='Chi-square distribution with df=10')

# Shade the area corresponding to a chi-square statistic of 15
x_fill = np.linspace(0, 15, 1000)
plt.fill_between(x_fill, stats.chi2.pdf(x_fill, df), color='skyblue', alpha=0.5, label='Chi-square statistic of 15')

# Add labels and title
plt.xlabel('Chi-square value')
plt.ylabel('Probability Density Function')
plt.title('Chi-square Distribution')

# Add legend
plt.legend()

# Show plot
plt.grid(True)
plt.show()

In [4]:
##Q7. A random sample of 1000 people was asked if they preferred Coke or Pepsi. Of the sample, 520 preferred Coke. Calculate a 99% confidence interval for the true proportion of people in the population who prefer Coke.

##A7. 

import statsmodels.stats.proportion as prop

# Sample size
n = 1000

# Number of individuals who preferred coke
x = 520

# Calculate the proportion
p_hat = x / n

# Calculate the confidence interval
conf_interval = prop.proportion_confint(x, n, alpha=0.01, method='normal')

print("99% Confidence Interval for the proportion of smokers:", conf_interval)

99% Confidence Interval for the proportion of smokers: (0.4793051576779699, 0.5606948423220302)


In [8]:
##Q8. A researcher hypothesizes that a coin is biased towards tails. They flip the coin 100 times and observe 45 tails. Conduct a chi-square goodness of fit test to determine if the observed frequencies match the expected frequencies of a fair coin. Use a significance level of 0.05.

##A8. To conduct a chi-square goodness of fit test to determine if the observed frequencies match the expected frequencies of a fair coin, you first need to specify the null hypothesis and the alternative hypothesis.

##Null hypothesis (H0): The coin is fair (i.e., the observed frequencies match the expected frequencies).

##Alternative hypothesis (H1): The coin is biased towards tails (i.e., the observed frequencies do not match the expected frequencies).

##Next, you calculate the expected frequencies assuming the coin is fair. For a fair coin, the expected frequency of heads and tails is 50 each out of 100 flips.

##Then, you compute the chi-square statistic using the formula:

##X^2=summation of ((observed frequency-expected frequency)^2)/exoected frequency

##Finally, you compare the computed chi-square statistic with the critical value from the chi-square distribution with k−1 degrees of freedom, where k is the number of categories (2 in this case: heads and tails). If the computed chi-square statistic exceeds the critical value, you reject the null hypothesis.

##Python code below:

from scipy.stats import chi2

# Observed frequencies
observed_freq = np.array([45, 55])  # 45 tails, 55 heads

# Expected frequencies assuming a fair coin
expected_freq = np.array([50, 50])  # 50 tails, 50 heads

# Compute the chi-square statistic
chi2_stat = np.sum((observed_freq - expected_freq) ** 2 / expected_freq)

# Degrees of freedom
degrees_of_freedom = len(observed_freq) - 1

# Calculate the p-value
p_value = 1 - chi2.cdf(chi2_stat, degrees_of_freedom)

# Significance level
alpha = 0.05

# Compare p-value with significance level
if p_value < alpha:
    print("Reject the null hypothesis. The coin is biased towards tails.")
else:
    print("Fail to reject the null hypothesis. The coin is fair.")

Fail to reject the null hypothesis. The coin is fair.


In [11]:
##Q9. A study was conducted to determine if there is an association between smoking status (smoker or non-smoker) and lung cancer diagnosis (yes or no). The results are shown in the contingency table below. Conduct a chi-square test for independence to determine if there is a significant association between smoking status and lung cancer diagnosis.

##A9. 

from scipy.stats import chi2_contingency

# Contingency table (smoking status vs. lung cancer diagnosis)
#             | Lung Cancer (Yes) | Lung Cancer (No)
# ------------|-------------------|-----------------
# Smoker      |        60         |        140
# Non-smoker  |        30         |        170

contingency_table = [[60, 140], [30, 170]]

# Perform the chi-square test for independence
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

# Significance level
alpha = 0.05

# Compare p-value with significance level
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant association between smoking status and lung cancer diagnosis.")
else:
    print("Fail to reject the null hypothesis. There is no significant association between smoking status and lung cancer diagnosis.")

print(chi2_stat)
print(expected)
print(p_value)

Reject the null hypothesis. There is a significant association between smoking status and lung cancer diagnosis.
12.057347670250895
[[ 45. 155.]
 [ 45. 155.]]
0.0005158863863703744


In [15]:
##Q10. A study was conducted to determine if the proportion of people who prefer milk chocolate, dark chocolate, or white chocolate is different in the U.S. versus the U.K. A random sample of 500 people from the U.S. and a random sample of 500 people from the U.K. were surveyed. The results are shown in the contingency table below. Conduct a chi-square test for independence to determine if there is a significant association between chocolate preference and country of origin. Use a significance level of 0.01.

##A10.

from scipy.stats import chi2_contingency

# Contingency table (chocolate preference vs. country of origin)
#             | Milk chocolate    | Dark chocolate  | White chocolate
# ------------|-------------------|-----------------|------------------
# US (n=500)  |        200        |        150      |      150
# UK (n=500)  |        225        |        175      |      100

contingency_table = [[200, 150, 150], [225, 175, 100]]

# Perform the chi-square test for independence
chi2_stat, p_value, dof, expected = chi2_contingency(contingency_table)

# Significance level
alpha = 0.01

# Compare p-value with significance level
if p_value < alpha:
    print("Reject the null hypothesis. There is a significant association between chocolate preference and country of origin.")
else:
    print("Fail to reject the null hypothesis. There is no significant association between chocolate preference and country of origin.")

print(chi2_stat)
print(expected)
print(p_value)

Reject the null hypothesis. There is a significant association between chocolate preference and country of origin.
13.393665158371041
[[212.5 162.5 125. ]
 [212.5 162.5 125. ]]
0.0012348168997745918


In [ ]:
##Q11. A random sample of 30 people was selected from a population with an unknown mean and standard deviation. The sample mean was found to be 72 and the sample standard deviation was found to be 10. Conduct a hypothesis test to determine if the population mean is significantly different from 70. Use a significance level of 0.05.

##A5. To conduct a hypothesis test to determine if the population mean is significantly different from 70, you can perform a one-sample t-test. Here's how you can do it:

##Formulate hypotheses:

##Null hypothesis (H0): The population mean is equal to 70 (μ = 70).
##Alternative hypothesis (H1): The population mean is not equal to 70 (μ ≠ 70).

##Choose significance level: Let's use a significance level of 0.05.

##Calculate the test statistic

##Determine the critical value: We'll find the critical value from the t-distribution with n−1 degrees of freedom.

##Compare the test statistic with the critical value and make a decision: If the absolute value of the test statistic exceeds the critical value, we reject the null hypothesis.

import numpy as np
from scipy.stats import t

# Sample mean
sample_mean = 72

# Population mean under the null hypothesis
population_mean = 70

# Sample standard deviation
sample_std_dev = 10

# Sample size
sample_size = 30

# Calculate the test statistic
t_statistic = (sample_mean - population_mean) / (sample_std_dev / np.sqrt(sample_size))

# Degrees of freedom
degrees_of_freedom = sample_size - 1

# Calculate the critical value (two-tailed test)
alpha = 0.05
critical_value = t.ppf(1 - alpha / 2, degrees_of_freedom)

# Compare the test statistic with the critical value
if np.abs(t_statistic) > critical_value:
    print("Reject the null hypothesis. The population mean is significantly different from 70.")
else:
    print("Fail to reject the null hypothesis. There is insufficient evidence to conclude that the population mean is significantly different from 70.")